"use client";
import { useMemo, useState } from "react";
import { PracticeRecorder } from "@/components/practice-recorder";

type Sentence = { id:string; sequence:number; start_time:number|null; end_time:number|null; original_text:string; translation:string; grammar_note:string; slang_note?:string; pronunciation_hint?:string; completed_at:string|null; is_favorite:boolean; is_difficult:boolean };
export function LessonPlayer({ sentences, videoUrl, lessonId }: { sentences: Sentence[]; videoUrl?: string; lessonId:string }) {
  const [index, setIndex] = useState(0); const [items, setItems] = useState(sentences); const current = items[index]; const completed = useMemo(() => items.filter(item => item.completed_at).length, [items]);
  const embedUrl = videoUrl ? `https://www.youtube.com/embed/${new URL(videoUrl).searchParams.get("v") ?? videoUrl.split("youtu.be/")[1]?.split("?")[0]}?start=${Math.floor(current?.start_time ?? 0)}&rel=0` : "";
  async function update(patch: {completed?:boolean;favorite?:boolean;difficult?:boolean}) { const response = await fetch(`/api/sentences/${current.id}`, {method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(patch)}); if (!response.ok) return; const next = await response.json(); setItems(items.map(item => item.id === current.id ? {...item, completed_at:next.completed_at, is_favorite:next.is_favorite, is_difficult:next.is_difficult} : item)); }
  if (!current) return null;
  return <div><div className="lesson-layout"><div className="feature" style={{padding:0,overflow:"hidden"}}><iframe title="Lesson video" src={embedUrl} style={{width:"100%",aspectRatio:"16/9",border:0}} allow="autoplay; encrypted-media"/><div style={{padding:18}}><div style={{display:"flex",justifyContent:"space-between",color:"var(--muted)",fontSize:13}}><span>Sentence {index+1} / {items.length}</span><span>{completed} learned · {Math.round(completed/items.length*100)}%</span></div><div style={{height:8,background:"var(--mint)",borderRadius:8,marginTop:10}}><div style={{height:"100%",width:`${completed/items.length*100}%`,background:"var(--green)",borderRadius:8}}/></div></div></div><article className="feature"><small style={{color:"var(--muted)"}}>Focus sentence</small><h2 style={{fontSize:32,margin:"12px 0"}}>“{current.original_text}”</h2><p><strong>Meaning:</strong> {current.translation}</p><p><strong>Grammar:</strong> {current.grammar_note}</p>{current.slang_note&&<p><strong>Natural expression:</strong> {current.slang_note}</p>}<p style={{color:"var(--green)"}}>Pronunciation: {current.pronunciation_hint}</p><div style={{display:"flex",gap:8,margin:"20px 0",flexWrap:"wrap"}}><button className="button secondary" onClick={()=>update({completed:!current.completed_at})}>{current.completed_at?"✓ Learned":"Mark learned"}</button><button className="button secondary" onClick={()=>update({favorite:!current.is_favorite})}>{current.is_favorite?"★ Saved":"☆ Save"}</button><button className="button secondary" onClick={()=>update({difficult:!current.is_difficult})}>{current.is_difficult?"! Difficult":"Mark difficult"}</button></div><PracticeRecorder sentenceId={current.id} targetText={current.original_text}/><div style={{display:"flex",justifyContent:"space-between",marginTop:22}}><button className="button secondary" disabled={index===0} onClick={()=>setIndex(index-1)}>← Previous</button><button className="button" disabled={index===items.length-1} onClick={()=>setIndex(index+1)}>Next →</button></div></article></div>{completed===items.length&&<div className="feature" style={{marginTop:18}}><h3>课程完成了 🎉</h3><p>你已经完成本课全部句子。</p><a className="button" href={`/learn/${lessonId}/complete`}>View summary →</a></div>}</div>;
}
