"use client";
import { useRef, useState } from "react";

export function PracticeRecorder({ sentenceId, targetText }: { sentenceId: string; targetText: string }) {
  const recorder = useRef<MediaRecorder | null>(null); const chunks = useRef<Blob[]>([]); const [recording, setRecording] = useState(false); const [result, setResult] = useState<{score:number;feedback:string;transcript:string}|null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function play() { setError(""); const response = await fetch("/api/tts", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({text:targetText}) }); if (!response.ok) { setError("无法播放示范音频"); return; } const audio = new Audio(URL.createObjectURL(await response.blob())); await audio.play(); }
  async function toggleRecording() { if (recording) { recorder.current?.stop(); setRecording(false); return; } try { setError(""); const stream = await navigator.mediaDevices.getUserMedia({ audio:true }); chunks.current=[]; const current = new MediaRecorder(stream); recorder.current=current; current.ondataavailable = event => chunks.current.push(event.data); current.onstop = async () => { stream.getTracks().forEach(track=>track.stop()); setBusy(true); const form = new FormData(); form.append("audio", new Blob(chunks.current, {type:"audio/webm"}), "practice.webm"); form.append("sentenceId", sentenceId); const response = await fetch("/api/practice", {method:"POST",body:form}); const payload = await response.json().catch(() => null); if (!response.ok) setError(payload?.error ?? "评分失败，请稍后再试"); else setResult(payload); setBusy(false); }; current.start(); setRecording(true); } catch { setError("无法访问麦克风，请检查浏览器权限。"); } }
  return <div style={{display:"flex",gap:10,alignItems:"center",flexWrap:"wrap"}}><button className="button secondary" onClick={play}>▶ Hear model</button><button className="button" onClick={toggleRecording} disabled={busy}>{busy?"Scoring…":recording?"■ Stop recording":"● Record yourself"}</button>{result&&<span style={{color:"var(--green)",fontSize:14}}>Score {result.score}/100 · {result.feedback}</span>}{error&&<span style={{color:"#b13a35",fontSize:14}}>{error}</span>}</div>;
}
