import Link from "next/link";
import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";

export default async function DashboardPage() {
  const supabase = await createSupabaseServerClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/auth/login");
  const { data: lessons } = await supabase.from("lessons").select("id,title,status,created_at,lesson_sentences(completed_at)").order("created_at", { ascending: false });
  const sentenceList = (lessons ?? []).flatMap(lesson => lesson.lesson_sentences as Array<{completed_at:string|null}>); const learned = sentenceList.filter(sentence => sentence.completed_at).length; const today = new Date().toDateString(); const learnedToday = sentenceList.filter(sentence => sentence.completed_at && new Date(sentence.completed_at).toDateString() === today).length;
  return <main className="shell"><nav className="nav"><Link className="brand" href="/"><span className="brand-mark">L</span><span>LingoFrame</span></Link><div style={{display:"flex",gap:10,alignItems:"center"}}><Link className="button" href="/learn/new">New lesson →</Link><form action="/auth/signout" method="post"><button className="button secondary" type="submit">Sign out</button></form></div></nav><div className="eyebrow">Your library</div><h1 style={{fontSize:56}}>Keep going.</h1><p className="lede">{user.email}</p><div className="feature-grid" style={{marginTop:28}}><article className="feature"><h3>{lessons?.length ?? 0}</h3><p>lessons created</p></article><article className="feature"><h3>{learned}</h3><p>sentences learned</p></article><article className="feature"><h3>{learnedToday}</h3><p>learned today</p></article><Link className="feature" href="/review/today"><h3>Today’s review →</h3><p>复习困难和到期句子</p></Link></div><div style={{display:"grid",gap:12,marginTop:34}}>{lessons?.length ? lessons.map(lesson=><Link className="feature" href={`/learn/${lesson.id}`} key={lesson.id}><h3>{lesson.title ?? "Untitled lesson"}</h3><p>{lesson.status} · {new Date(lesson.created_at).toLocaleDateString()}</p></Link>) : <article className="feature"><h3>Your first lesson is waiting.</h3><p>Paste a video and start building your personal English library.</p></article>}</div></main>;
}
